version: "3.8"

networks:
  app-network:
    driver: bridge

services:
  nginx:
    build: ./nginx
    container_name: nginx
    ports:
      - "80:80"
    networks:
      - app-network
    depends_on:
      - frontend
      - flaskapp

  frontend:
    build: ./app/frontend
    ports:
      - "3000:3000"
    depends_on:
      - flaskapp
    networks:
      - app-network
    container_name: frontend
    working_dir: /home/frontend
    env_file:
      - ./app/frontend/.env
    volumes:
      - ./app/frontend:/home/frontend

  flaskapp:
    build:
      context: ./app/backend
    restart: always
    networks:
      - app-network
    working_dir: /home/backend
    container_name: flaskapp
    ports:
      - "8005:8005"
    volumes:
      - ./app/backend:/home/backend
    depends_on:
      - postgresql
    env_file:
      - ./app/backend/.env

  postgresql:
    image: postgres:13
    networks:
      - app-network
    container_name: test_postgresql
    restart: always
    env_file:
      - ./app/backend/.env
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
